name: deploy on aliyun ecs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 切换分支
    - name: Checkout
      uses: actions/checkout@master
    # 下载 git submodule
    - uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    # 使用 node:10
    - name: use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    # Deploy
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: "121.196.40.246"
          REMOTE_USER: "root"
          TARGET: "/usr/share/nginx/pdfjshtml/"